/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AuditFlowStaking {
  export type TierInfoStruct = {
    tierId: BigNumberish;
    name: string;
    description: string;
    baseTokens: BigNumberish;
    maxTokens: BigNumberish;
    featureAccess: BigNumberish[];
    minStakeDays: BigNumberish;
    maxStakeDays: BigNumberish;
    yieldRate: BigNumberish;
  };

  export type TierInfoStructOutput = [
    tierId: bigint,
    name: string,
    description: string,
    baseTokens: bigint,
    maxTokens: bigint,
    featureAccess: bigint[],
    minStakeDays: bigint,
    maxStakeDays: bigint,
    yieldRate: bigint
  ] & {
    tierId: bigint;
    name: string;
    description: string;
    baseTokens: bigint;
    maxTokens: bigint;
    featureAccess: bigint[];
    minStakeDays: bigint;
    maxStakeDays: bigint;
    yieldRate: bigint;
  };

  export type UserTierInfoStruct = {
    tierId: BigNumberish;
    tierName: string;
    tierDescription: string;
    hasActiveStake: boolean;
    stakedAmount: BigNumberish;
    stakeStartTime: BigNumberish;
    stakeEndTime: BigNumberish;
    daysRemaining: BigNumberish;
    accruedYield: BigNumberish;
    accessibleFeatures: BigNumberish[];
  };

  export type UserTierInfoStructOutput = [
    tierId: bigint,
    tierName: string,
    tierDescription: string,
    hasActiveStake: boolean,
    stakedAmount: bigint,
    stakeStartTime: bigint,
    stakeEndTime: bigint,
    daysRemaining: bigint,
    accruedYield: bigint,
    accessibleFeatures: bigint[]
  ] & {
    tierId: bigint;
    tierName: string;
    tierDescription: string;
    hasActiveStake: boolean;
    stakedAmount: bigint;
    stakeStartTime: bigint;
    stakeEndTime: bigint;
    daysRemaining: bigint;
    accruedYield: bigint;
    accessibleFeatures: bigint[];
  };
}

export interface AuditFlowStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAY_IN_SECONDS"
      | "EMERGENCY_PENALTY"
      | "MAX_STAKE_DAYS"
      | "MIN_STAKE_DAYS"
      | "MULTIPLIER_BASE"
      | "MULTIPLIER_DECAY_RATE"
      | "MULTIPLIER_MAX"
      | "TOKEN_DECIMALS"
      | "YIELD_RATE"
      | "calculateAccruedYield"
      | "calculateRequiredStake"
      | "calculateRequiredStakeByTierId"
      | "daoWallet"
      | "emergencyUnstake"
      | "getAllTiers"
      | "getAllowance"
      | "getContractBalance"
      | "getMyTierInfo"
      | "getTotalStakedTokens"
      | "getUserStake"
      | "getUserTokenBalance"
      | "hasFeatureAccess"
      | "liskToken"
      | "owner"
      | "positions"
      | "recoverERC20"
      | "renounceOwnership"
      | "setDaoWallet"
      | "stake"
      | "tierConfigs"
      | "totalStakedLSK"
      | "totalStakers"
      | "totalYieldContributed"
      | "transferOwnership"
      | "unstake"
      | "updateTier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DaoWalletUpdated"
      | "EmergencyUnstake"
      | "OwnershipTransferred"
      | "Staked"
      | "TierUpdated"
      | "Unstaked"
      | "YieldClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DAY_IN_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_PENALTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_STAKE_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_STAKE_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MULTIPLIER_BASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MULTIPLIER_DECAY_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MULTIPLIER_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "YIELD_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAccruedYield",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequiredStake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequiredStakeByTierId",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "daoWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyUnstake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTiers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyTierInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStakedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTokenBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasFeatureAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "liskToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDaoWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tierConfigs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStakedLSK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStakers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalYieldContributed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unstake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTier",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DAY_IN_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_PENALTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STAKE_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_STAKE_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MULTIPLIER_BASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MULTIPLIER_DECAY_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MULTIPLIER_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "YIELD_RATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateAccruedYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequiredStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequiredStakeByTierId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "daoWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnstake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyTierInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStakedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasFeatureAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liskToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDaoWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tierConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStakedLSK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStakers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalYieldContributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateTier", data: BytesLike): Result;
}

export namespace DaoWalletUpdatedEvent {
  export type InputTuple = [oldWallet: AddressLike, newWallet: AddressLike];
  export type OutputTuple = [oldWallet: string, newWallet: string];
  export interface OutputObject {
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyUnstakeEvent {
  export type InputTuple = [
    user: AddressLike,
    principalReturned: BigNumberish,
    penalty: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    principalReturned: bigint,
    penalty: bigint
  ];
  export interface OutputObject {
    user: string;
    principalReturned: bigint;
    penalty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    user: AddressLike,
    tier: BigNumberish,
    amount: BigNumberish,
    durationDays: BigNumberish,
    unlocksAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tier: bigint,
    amount: bigint,
    durationDays: bigint,
    unlocksAt: bigint
  ];
  export interface OutputObject {
    user: string;
    tier: bigint;
    amount: bigint;
    durationDays: bigint;
    unlocksAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierUpdatedEvent {
  export type InputTuple = [
    tier: BigNumberish,
    baseTokens: BigNumberish,
    maxTokens: BigNumberish
  ];
  export type OutputTuple = [
    tier: bigint,
    baseTokens: bigint,
    maxTokens: bigint
  ];
  export interface OutputObject {
    tier: bigint;
    baseTokens: bigint;
    maxTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    user: AddressLike,
    principal: BigNumberish,
    yieldToDao: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    principal: bigint,
    yieldToDao: bigint
  ];
  export interface OutputObject {
    user: string;
    principal: bigint;
    yieldToDao: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditFlowStaking extends BaseContract {
  connect(runner?: ContractRunner | null): AuditFlowStaking;
  waitForDeployment(): Promise<this>;

  interface: AuditFlowStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAY_IN_SECONDS: TypedContractMethod<[], [bigint], "view">;

  EMERGENCY_PENALTY: TypedContractMethod<[], [bigint], "view">;

  MAX_STAKE_DAYS: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE_DAYS: TypedContractMethod<[], [bigint], "view">;

  MULTIPLIER_BASE: TypedContractMethod<[], [bigint], "view">;

  MULTIPLIER_DECAY_RATE: TypedContractMethod<[], [bigint], "view">;

  MULTIPLIER_MAX: TypedContractMethod<[], [bigint], "view">;

  TOKEN_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  YIELD_RATE: TypedContractMethod<[], [bigint], "view">;

  calculateAccruedYield: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  calculateRequiredStake: TypedContractMethod<
    [tier: BigNumberish, durationDays: BigNumberish],
    [bigint],
    "view"
  >;

  calculateRequiredStakeByTierId: TypedContractMethod<
    [tierId: BigNumberish, durationDays: BigNumberish],
    [bigint],
    "view"
  >;

  daoWallet: TypedContractMethod<[], [string], "view">;

  emergencyUnstake: TypedContractMethod<[], [void], "nonpayable">;

  getAllTiers: TypedContractMethod<
    [],
    [AuditFlowStaking.TierInfoStructOutput[]],
    "view"
  >;

  getAllowance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getMyTierInfo: TypedContractMethod<
    [],
    [AuditFlowStaking.UserTierInfoStructOutput],
    "view"
  >;

  getTotalStakedTokens: TypedContractMethod<[], [bigint], "view">;

  getUserStake: TypedContractMethod<
    [user: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        hasActiveStake: boolean;
        tierId: bigint;
        amountStaked: bigint;
        stakedAt: bigint;
        unlocksAt: bigint;
        accruedYield: bigint;
        daysRemaining: bigint;
      }
    ],
    "view"
  >;

  getUserTokenBalance: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  hasFeatureAccess: TypedContractMethod<
    [user: AddressLike, featureId: BigNumberish],
    [boolean],
    "view"
  >;

  liskToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  positions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        tier: bigint;
        amountStaked: bigint;
        stakedAt: bigint;
        unlocksAt: bigint;
        claimedYield: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  recoverERC20: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDaoWallet: TypedContractMethod<
    [_daoWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [tierId: BigNumberish, durationDays: BigNumberish],
    [void],
    "nonpayable"
  >;

  tierConfigs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint] & {
        baseTokens: bigint;
        maxTokens: bigint;
        name: string;
        description: string;
        yieldRate: bigint;
      }
    ],
    "view"
  >;

  totalStakedLSK: TypedContractMethod<[], [bigint], "view">;

  totalStakers: TypedContractMethod<[], [bigint], "view">;

  totalYieldContributed: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[], [void], "nonpayable">;

  updateTier: TypedContractMethod<
    [
      tierId: BigNumberish,
      baseTokens: BigNumberish,
      maxTokens: BigNumberish,
      yieldRate: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAY_IN_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_PENALTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STAKE_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MULTIPLIER_BASE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MULTIPLIER_DECAY_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MULTIPLIER_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "YIELD_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateAccruedYield"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateRequiredStake"
  ): TypedContractMethod<
    [tier: BigNumberish, durationDays: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateRequiredStakeByTierId"
  ): TypedContractMethod<
    [tierId: BigNumberish, durationDays: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "daoWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyUnstake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllTiers"
  ): TypedContractMethod<[], [AuditFlowStaking.TierInfoStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAllowance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyTierInfo"
  ): TypedContractMethod<
    [],
    [AuditFlowStaking.UserTierInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalStakedTokens"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserStake"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        hasActiveStake: boolean;
        tierId: bigint;
        amountStaked: bigint;
        stakedAt: bigint;
        unlocksAt: bigint;
        accruedYield: bigint;
        daysRemaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTokenBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasFeatureAccess"
  ): TypedContractMethod<
    [user: AddressLike, featureId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "liskToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        tier: bigint;
        amountStaked: bigint;
        stakedAt: bigint;
        unlocksAt: bigint;
        claimedYield: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recoverERC20"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDaoWallet"
  ): TypedContractMethod<[_daoWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [tierId: BigNumberish, durationDays: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tierConfigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint] & {
        baseTokens: bigint;
        maxTokens: bigint;
        name: string;
        description: string;
        yieldRate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalStakedLSK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStakers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalYieldContributed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTier"
  ): TypedContractMethod<
    [
      tierId: BigNumberish,
      baseTokens: BigNumberish,
      maxTokens: BigNumberish,
      yieldRate: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DaoWalletUpdated"
  ): TypedContractEvent<
    DaoWalletUpdatedEvent.InputTuple,
    DaoWalletUpdatedEvent.OutputTuple,
    DaoWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyUnstake"
  ): TypedContractEvent<
    EmergencyUnstakeEvent.InputTuple,
    EmergencyUnstakeEvent.OutputTuple,
    EmergencyUnstakeEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "TierUpdated"
  ): TypedContractEvent<
    TierUpdatedEvent.InputTuple,
    TierUpdatedEvent.OutputTuple,
    TierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;
  getEvent(
    key: "YieldClaimed"
  ): TypedContractEvent<
    YieldClaimedEvent.InputTuple,
    YieldClaimedEvent.OutputTuple,
    YieldClaimedEvent.OutputObject
  >;

  filters: {
    "DaoWalletUpdated(address,address)": TypedContractEvent<
      DaoWalletUpdatedEvent.InputTuple,
      DaoWalletUpdatedEvent.OutputTuple,
      DaoWalletUpdatedEvent.OutputObject
    >;
    DaoWalletUpdated: TypedContractEvent<
      DaoWalletUpdatedEvent.InputTuple,
      DaoWalletUpdatedEvent.OutputTuple,
      DaoWalletUpdatedEvent.OutputObject
    >;

    "EmergencyUnstake(address,uint256,uint256)": TypedContractEvent<
      EmergencyUnstakeEvent.InputTuple,
      EmergencyUnstakeEvent.OutputTuple,
      EmergencyUnstakeEvent.OutputObject
    >;
    EmergencyUnstake: TypedContractEvent<
      EmergencyUnstakeEvent.InputTuple,
      EmergencyUnstakeEvent.OutputTuple,
      EmergencyUnstakeEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Staked(address,uint8,uint256,uint256,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "TierUpdated(uint8,uint256,uint256)": TypedContractEvent<
      TierUpdatedEvent.InputTuple,
      TierUpdatedEvent.OutputTuple,
      TierUpdatedEvent.OutputObject
    >;
    TierUpdated: TypedContractEvent<
      TierUpdatedEvent.InputTuple,
      TierUpdatedEvent.OutputTuple,
      TierUpdatedEvent.OutputObject
    >;

    "Unstaked(address,uint256,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;

    "YieldClaimed(address,uint256)": TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
    YieldClaimed: TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
  };
}
