/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingSol from "./staking.sol";
export type { stakingSol };
import type * as testTokenSol from "./testToken.sol";
export type { testTokenSol };
